version: "3.8"

services:
  whoogle-search:
    image: benbusby/whoogle-search:latest
    container_name: whoogle-search
    restart: unless-stopped
    ports:
      - 8003:5000
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    # user debian-tor from tor package
    user: whoogle
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    env_file:
      - stack.env
