version: "3.9"

services:
  timetagger:
    image: ghcr.io/almarklein/timetagger
    ports:
      - "3031:80"
    volumes:
      - $TIME_TAGGER_VOLUME:/root/_timetagger
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
      - TIMETAGGER_CREDENTIALS=test:$$2a$$08$$FfbkiZDWqGaSY8Ej0JCnSOujBNBjC5G35OIlJ1LsdQwLs3x7DOi12
