version: "3.9"

services:
  sqldb:
    image: mysql:8.3
    volumes:
      - $KIMAI_VOLUME_MYSQL:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=$DATABASE_NAME
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:apache
    volumes:
      - $KIMAI_VOLUME_DATA:/opt/kimai/var/data
      - $KIMAI_VOLUME_PLUGINS:/opt/kimai/var/plugins
    ports:
      - 8032:8001
    environment:
      - ADMINMAIL=$ADMIN_EMAIL
      - ADMINPASS=$ADMIN_PASSWORD
      # - "DATABASE_URL=mysql://$DATABASE_USER:$DATABASE_PASSWORD@sqldb/$DATABASE_NAME?charset=utf8mb4&serverVersion=8.3.0"
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@sqldb/${DATABASE_NAME}?charset=utf8mb4&serverVersion=8.3.0
    restart: unless-stopped
