version: "3.8"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.19.4-alpine
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/volumes/portainer:/data
