version: "3.9"

services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    container_name: wakapi
    ports:
      - 3092:3000
    restart: always
    # Environments: https://github.com/muety/wakapi?tab=readme-ov-file#-configuration-options
    environment:
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_USER: "wakapi"
      WAKAPI_DB_PASSWORD: ${POSTGRES_PASSWORD}
      WAKAPI_DB_HOST: "db"
      WAKAPI_DB_PORT: "5432"
      ENVIRONMENT: "prod"
      WAKAPI_PASSWORD_SALT: ${SALT}

      # Features
      WAKAPI_LEADERBOARD_ENABLED: "fallse"
      WAKAPI_ALLOW_SIGNUP: "false"
      WAKAPI_INVITE_CODES: "false"
      WAKAPI_DISABLE_FRONTPAGE: "true"
      WAKAPI_EXPOSE_METRICS: "false"

  db:
    image: postgres:12.3
    container_name: postgres
    environment:
      POSTGRES_USER: "wakapi"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "wakapi"
    volumes:
      - ./docker/volumes/wakatime/postgres:/var/lib/postgresql/data
